"""Content data for the 'Nếu... thì sao' (what-if) reel series, days 2–7.
Each day: title, slug, story, and 7 scenes = (narrator_vn, image_prompt_en, motion_prompt_en).
Consumed by scripts/whatif_produce.py.
"""

STYLE = ("cinematic, hyper-realistic, photorealistic, dramatic atmospheric lighting, "
         "epic scale, vertical 9:16, no text")

DAYS = {
    "day2": {
        "title": "Nếu trọng lực biến mất 5 giây",
        "slug": "neu_trong_luc_bien_mat",
        "story": "What-if: trọng lực Trái Đất biến mất trong 5 giây.",
        "scenes": [
            ("Nếu trọng lực trên Trái Đất biến mất chỉ trong năm giây, mọi thứ không được cố định sẽ lập tức bay lên không trung.",
             "people, cars and loose objects on a city street beginning to lift off the ground and float upward, chaotic",
             "people and cars on a city street slowly lifting off the ground, debris rising into the air, chaotic, slow"),
            ("Trong khoảnh khắc đầu tiên, con người, xe cộ và vô số mảnh vỡ rời khỏi mặt đất, trôi lơ lửng hỗn loạn.",
             "cars, people and rooftops floating in mid-air above a city, surreal chaos, dramatic sky",
             "cars and people floating mid-air above a city, drifting upward chaotically, surreal, slow"),
            ("Đại dương dâng lên thành những cột nước khổng lồ, bầu khí quyển bắt đầu trôi dạt dần ra ngoài không gian.",
             "giant columns of ocean water rising into the sky, atmosphere drifting away, epic surreal seascape",
             "enormous columns of seawater rising into the sky, mist drifting upward, epic surreal, slow"),
            ("Năm giây trôi qua, trọng lực đột ngột trở lại, và tất cả rơi sầm xuống mặt đất với một lực kinh hoàng.",
             "everything crashing back down to the ground at once, massive impact, dust clouds, dramatic aftermath",
             "floating cars and debris suddenly crashing back to the ground, dust erupting, violent impact, dramatic"),
            ("Các thành phố biến thành đống đổ nát chỉ trong tích tắc, mặt đất rung chuyển bởi hàng triệu vụ va chạm.",
             "a city reduced to rubble after impact, collapsed buildings, dust and debris everywhere, epic desolate",
             "a ruined city settling after impact, dust clouds drifting over collapsed buildings, desolate, slow"),
            ("Chỉ những ai đang ngồi yên và thắt chặt mình vào vật cố định mới có cơ hội sống sót qua năm giây đó.",
             "a lone survivor strapped to a heavy fixed structure amid wreckage, faint light, grim atmosphere",
             "a survivor gripping a fixed structure amid wreckage, dust settling around them, grim, slow push-in"),
            ("Chỉ năm giây không trọng lực cũng đủ để xoá sổ gần như toàn bộ nền văn minh của nhân loại.",
             "a devastated Earth landscape under a vast sky, silent ruins stretching to the horizon, haunting epic",
             "a devastated ruined landscape stretching to the horizon under a vast sky, haunting, very slow aerial drift"),
        ],
    },
    "day3": {
        "title": "Nếu đại dương cạn khô",
        "slug": "neu_dai_duong_can_kho",
        "story": "What-if: toàn bộ đại dương Trái Đất cạn khô.",
        "scenes": [
            ("Nếu toàn bộ đại dương trên Trái Đất đột nhiên cạn khô, bạn sẽ nhìn thấy đáy biển lần đầu tiên trong lịch sử.",
             "ocean water vanishing to reveal a vast empty muddy seabed, stranded ships, surreal desolate",
             "Slow cinematic aerial push-in over rusty shipwrecks stranded on a vast cracked muddy seabed, thin mist drifting low, faint dust, cold dawn light, eerie desolate"),
            ("Hàng triệu xác tàu đắm và sinh vật biển khổng lồ mắc cạn lộ ra trên lớp bùn đáy đại dương mênh mông.",
             "countless shipwrecks and giant stranded sea creatures on an endless muddy ocean floor, eerie desolate",
             "a vast exposed seabed with shipwrecks and stranded creatures, mist drifting, eerie, slow pan"),
            ("Những rãnh đại dương sâu nhất hiện ra như các vực thẳm khổng lồ ăn sâu vào lòng hành tinh.",
             "a colossal deep ocean trench revealed as an abyss cutting into the planet, epic dramatic scale",
             "a colossal deep ocean trench revealed, dark abyss, mist rising from the depths, epic, slow push-in"),
            ("Không còn nước biển bốc hơi, mưa ngừng rơi, các lục địa dần biến thành những sa mạc muối khô cằn.",
             "continents turning into vast cracked salt deserts under a harsh sky, dead dry wasteland, bleak",
             "a vast cracked salt desert under harsh light, dust blowing across the wasteland, bleak, slow"),
            ("Các thành phố ven biển từng sầm uất giờ trơ trọi giữa hoang mạc, cách xa bờ nước hàng trăm cây số.",
             "a former coastal city stranded alone in a vast dry desert far from any water, desolate epic",
             "a coastal city stranded in an endless desert, dust drifting past empty streets, desolate, slow"),
            ("Loài người tuyệt vọng đào sâu tìm nước ngầm, những cuộc di cư khổng lồ bắt đầu khắp hành tinh.",
             "long lines of human refugees crossing a cracked desert searching for water, grim, dramatic sky",
             "a long line of refugees trekking across a cracked desert under a harsh sky, grim, slow"),
            ("Bảy mươi phần trăm hành tinh xanh từng tràn đầy sự sống nay trở thành một nấm mồ khô cằn im lặng.",
             "planet Earth as a dry brown lifeless sphere seen from space, oceans gone, haunting cosmic",
             "Earth as a dry brown lifeless sphere in space, no oceans, haunting, very slow zoom out"),
        ],
    },
    "day4": {
        "title": "Nếu loài người biến mất ngày mai",
        "slug": "neu_loai_nguoi_bien_mat",
        "story": "What-if: toàn bộ loài người biến mất sau một đêm.",
        "scenes": [
            ("Nếu sáng mai toàn bộ loài người đột nhiên biến mất, các thành phố vẫn đứng đó nhưng không còn một bóng người.",
             "a completely empty city street with no people, abandoned cars, eerie silent daylight",
             "an empty city street, abandoned cars, papers drifting in the wind, eerie silent, slow"),
            ("Chỉ sau vài ngày, lưới điện sụp đổ, đèn đường tắt ngấm, và thú hoang bắt đầu lang thang vào phố.",
             "wild animals wandering through a dark abandoned city at night, dead streetlights, eerie",
             "wild animals wandering an abandoned dark city street, eerie moonlight, slow"),
            ("Sau vài năm, cây leo và rễ cây phủ kín các toà nhà chọc trời, thiên nhiên bắt đầu đòi lại đô thị.",
             "skyscrapers overgrown with vines and plants, nature reclaiming a city, green overgrowth, atmospheric",
             "overgrown skyscrapers covered in vines, plants swaying, nature reclaiming the city, slow"),
            ("Đường cao tốc nứt vỡ thành rừng, thú rừng tự do đi lại nơi từng là trung tâm thành phố nhộn nhịp.",
             "a cracked overgrown highway turned into forest, deer walking where traffic once was, lush atmospheric",
             "a cracked highway overgrown into forest, deer walking through, sunlight filtering, slow"),
            ("Các công trình bê tông sụp đổ dần, rừng rậm nuốt chửng những gì còn sót lại của nền văn minh.",
             "collapsing concrete buildings swallowed by dense jungle, ruins overtaken by forest, epic atmospheric",
             "crumbling buildings swallowed by jungle, vegetation overtaking ruins, atmospheric, slow"),
            ("Chỉ còn tượng đài đá và rác nhựa tồn tại hàng nghìn năm, dấu vết cuối cùng rằng chúng ta từng hiện diện.",
             "a weathered stone monument standing alone in overgrown wilderness, last trace of humanity, haunting",
             "a weathered stone monument alone in wilderness, vines creeping over it, haunting, slow push-in"),
            ("Trái Đất không hề cần chúng ta, chỉ vài thế kỷ là đủ để nó xanh tươi trở lại như chưa từng có loài người.",
             "a lush green Earth landscape with overgrown ruins barely visible, thriving nature, serene haunting",
             "a lush green landscape with ruins barely visible under forest, birds flying, serene, slow aerial"),
        ],
    },
    "day5": {
        "title": "Nếu Trái Đất ngừng quay",
        "slug": "neu_trai_dat_ngung_quay",
        "story": "What-if: Trái Đất đột ngột ngừng quay.",
        "scenes": [
            ("Nếu Trái Đất đột ngột ngừng quay, mọi thứ trên bề mặt sẽ bị văng đi theo quán tính với vận tốc khủng khiếp.",
             "everything on Earth's surface violently flung sideways by inertia, massive winds, chaos, dramatic",
             "trees, buildings and debris violently swept sideways by inertia, massive wind, chaos, dramatic"),
            ("Những cơn gió siêu bão hơn một nghìn cây số mỗi giờ quét sạch mọi thứ trên đường đi của chúng.",
             "supersonic hurricane winds tearing across a landscape, everything swept away, apocalyptic, dramatic",
             "supersonic winds tearing across a landscape, debris flying, apocalyptic, fast dramatic"),
            ("Các đại dương khổng lồ dồn về hai cực, nhấn chìm một nửa hành tinh dưới những biển nước mênh mông.",
             "massive oceans surging toward the poles flooding continents, giant waves, epic catastrophic",
             "massive ocean waters surging across land toward the poles, giant waves, epic, slow"),
            ("Một nửa Trái Đất chìm trong ngày dài bất tận cháy nắng, nửa còn lại đóng băng trong đêm vĩnh cửu.",
             "a planet split between a scorched sunlit half and a frozen dark half, dramatic cosmic contrast",
             "Earth split between scorching daylight and frozen darkness, dramatic cosmic, slow"),
            ("Tại ranh giới giữa ngày và đêm vĩnh cửu, bão tố không bao giờ ngừng gào thét dọc khắp hành tinh.",
             "a permanent storm wall raging along the twilight boundary between the day and night side, epic dramatic",
             "a towering wall of storms raging along the day-night boundary, lightning, epic, slow"),
            ("Sự sống chỉ còn sót lại ở dải chạng vạng hẹp, nơi duy nhất nhiệt độ vẫn đủ để con người tồn tại.",
             "a narrow twilight zone with faint survivable light, a small human settlement, bleak, atmospheric",
             "a narrow twilight zone with dim light, a small settlement, storms on the horizon, bleak, slow"),
            ("Một vòng quay tưởng chừng vô hình lại chính là thứ duy nhất giữ cho cả thế giới này sống sót.",
             "Earth seen from space, half lit half dark, hanging motionless in the void, haunting cosmic",
             "Earth from space half-lit half-dark, motionless in the void, stars behind, haunting, very slow"),
        ],
    },
    "day6": {
        "title": "Nếu bạn không bao giờ ngủ lại được",
        "slug": "neu_khong_bao_gio_ngu",
        "story": "What-if body-horror: mất hoàn toàn khả năng ngủ (dựa bệnh FFI).",
        "scenes": [
            ("Nếu một ngày bạn mất hoàn toàn khả năng ngủ, cơ thể bạn sẽ bắt đầu một cuộc đếm ngược lặng lẽ đến cái chết.",
             "a person with wide sleepless bloodshot eyes lying awake in the dark, eerie clinical, unsettling",
             "a face with wide sleepless eyes in the dark, faint twitching, eerie clinical, slow push-in"),
            ("Sang ngày thứ ba không ngủ, ảo giác bắt đầu xuất hiện, ranh giới giữa thực và mộng dần tan biến.",
             "a disoriented person surrounded by faint surreal hallucinations in a dim room, unsettling distorted",
             "a dim room warping with faint surreal hallucinations around a person, distorted, slow drift"),
            ("Sau hai tuần, não bộ không thể tự dọn dẹp chất thải, các tế bào thần kinh bắt đầu tổn thương vĩnh viễn.",
             "a glowing human brain with damaged neurons and waste building up, clinical macro scientific, ominous",
             "a glowing human brain, neurons flickering and dimming, waste accumulating, clinical macro, slow"),
            ("Cơ thể suy sụp nhanh chóng, run rẩy và kiệt quệ, dù tâm trí vẫn hoàn toàn tỉnh táo trong nỗi sợ hãi.",
             "a frail trembling person deteriorating yet wide awake, gaunt and exhausted, grim clinical light",
             "a frail trembling figure, gaunt and exhausted but awake, faint shaking, grim, slow push-in"),
            ("Vùng đồi thị, công tắc giấc ngủ của não, bị ăn mòn dần thành những lỗ rỗng li ti không thể phục hồi.",
             "a cross-section of a human brain with the thalamus eaten into tiny holes, clinical macro, ominous",
             "a brain cross-section with the thalamus riddled with holes, slow clinical zoom, ominous"),
            ("Không một loại thuốc nào có thể chữa khỏi, người bệnh chỉ còn biết chờ đợi hồi kết không thể tránh khỏi.",
             "empty medicine vials beside a hospital bed in dim light, hopeless clinical atmosphere, somber",
             "empty medicine vials beside a dim hospital bed, faint light flickering, hopeless, slow"),
            ("Giấc ngủ không chỉ là nghỉ ngơi, nó âm thầm giữ cho bạn sống qua mỗi đêm mà bạn không hề hay biết.",
             "a peaceful sleeping silhouette dissolving into darkness, haunting symbolic, soft eerie light",
             "a sleeping silhouette slowly dissolving into darkness, haunting, very slow drift"),
        ],
    },
    "day7": {
        "title": "Nếu Mặt Trăng rơi xuống Trái Đất",
        "slug": "neu_mat_trang_roi",
        "story": "What-if: Mặt Trăng rơi về phía Trái Đất.",
        "scenes": [
            ("Nếu Mặt Trăng bắt đầu rơi về phía Trái Đất, nó sẽ lớn dần đến mức che kín gần như cả bầu trời của bạn.",
             "a giant Moon looming enormous in the sky over a city, filling the horizon, awe terrifying dramatic",
             "an enormous Moon looming larger in the sky over a city, slowly growing, awe terrifying, slow"),
            ("Lực hấp dẫn khổng lồ kéo nước biển dâng lên thành những đợt thuỷ triều nhấn chìm mọi bờ biển.",
             "colossal tidal waves rising and flooding a coastline as a huge Moon looms above, epic catastrophic",
             "colossal tidal waves surging over a coastline under a giant Moon, epic catastrophic, slow"),
            ("Lực hút biến dạng cả lớp vỏ Trái Đất, động đất và núi lửa bùng nổ dữ dội trên khắp hành tinh.",
             "global earthquakes and erupting volcanoes under a massive Moon, fiery cracks across the land, epic",
             "erupting volcanoes and cracking earth under a giant Moon, fire and smoke, epic, dramatic slow"),
            ("Khi đến quá gần, chính lực hấp dẫn của Trái Đất xé vỡ Mặt Trăng thành một vành đai đá khổng lồ.",
             "the Moon breaking apart into a massive ring of rocky debris around Earth, epic cosmic dramatic",
             "the Moon shattering into a vast ring of debris around Earth, fragments drifting, epic cosmic, slow"),
            ("Hàng triệu mảnh thiên thạch bốc cháy lao xuống, biến cả bầu trời thành một cơn mưa lửa rực đỏ.",
             "a sky full of burning meteors raining down over a landscape, fiery red apocalyptic, dramatic",
             "countless burning meteors streaking down across a red sky, raining fire, apocalyptic, dramatic"),
            ("Loài người trú ẩn sâu dưới lòng đất khi bầu trời rực cháy và mặt đất rung chuyển không ngừng nghỉ.",
             "humans sheltering deep underground as fire rains above, dark bunker, faint light, grim dramatic",
             "people sheltering in a dark underground bunker, dust falling, faint light flickering, grim, slow"),
            ("Người bạn đồng hành bốn tỉ năm của Trái Đất cũng chính là kẻ có thể kết liễu nó chỉ trong một đêm.",
             "a fire-scarred Earth glowing surrounded by a ring of lunar debris in space, haunting cosmic",
             "a fire-scarred Earth ringed by lunar debris in space, glowing embers, haunting, very slow zoom out"),
        ],
    },
}
