"""Content data for 'Nếu... thì sao' WEEK 3 (day15–day21). Same shape as whatif_days.py:
each day = title, slug, story, 7 scenes = (narrator_vn, image_prompt_en, motion_prompt_en).
Motion = camera + atmospheric (animatable from the still). Merged via whatif_produce.py.
"""

DAYS = {
    "day15": {
        "title": "Nếu siêu bão Mặt Trời đánh Trái Đất",
        "slug": "neu_bao_mat_troi",
        "story": "What-if: một cơn bão Mặt Trời cực mạnh (Carrington) đánh thẳng Trái Đất.",
        "scenes": [
            ("Nếu một cơn bão Mặt Trời cực mạnh như sự kiện Carrington đánh thẳng vào Trái Đất, thế giới hiện đại có thể sụp đổ trong vài giờ.",
             "a massive solar flare erupting from the Sun toward Earth, glowing plasma arc, cosmic dramatic",
             "a massive solar flare slowly erupting from the Sun, glowing plasma swelling, slow cosmic ominous"),
            ("Chỉ vài phút sau, bầu trời khắp nơi rực sáng cực quang, từ hai cực cho tới tận vùng xích đạo nhiệt đới.",
             "brilliant auroras filling the sky over a tropical city skyline at night, green and red light, surreal",
             "shimmering auroras rippling over a city skyline at night, slow, surreal beautiful ominous"),
            ("Dòng điện cảm ứng khổng lồ đốt cháy máy biến áp và lưới điện, cả châu lục chìm vào bóng tối cùng lúc.",
             "a darkened city skyline with sparking failing transformers, blackout, dramatic night",
             "a vast city going dark block by block, faint sparks fading, slow ominous"),
            ("Vệ tinh hỏng hàng loạt, định vị, liên lạc và internet toàn cầu tê liệt chỉ trong tích tắc.",
             "satellites sparking and drifting dead in orbit above a dark Earth, cosmic dramatic",
             "a satellite sparking and tumbling dead in orbit, dark Earth below, slow dramatic"),
            ("Không điện, hệ thống nước, bệnh viện và chuỗi cung ứng thực phẩm sụp đổ chỉ sau vài ngày ngắn ngủi.",
             "a dark silent hospital corridor lit only by faint emergency light, stalled infrastructure, grim",
             "slow push-in down a dark hospital corridor lit by faint emergency light, grim still"),
            ("Loài người bất ngờ bị đẩy về thời chưa có điện, loay hoay sống sót giữa thế giới đã quên cách đó.",
             "people gathered around candlelight and fire in a dark powerless city street at night, grim atmospheric",
             "people huddled around candlelight in a dark powerless street, flames flickering, slow grim"),
            ("Một cơn bão vô hình từ Mặt Trời cũng đủ kéo nền văn minh hiện đại lùi lại cả trăm năm.",
             "a dark Earth at night from space with almost no city lights, faint aurora glow, haunting cosmic",
             "Earth at night from space, almost no lights, faint aurora glow, slow zoom out, haunting"),
        ],
    },
    "day16": {
        "title": "Nếu Sao Mộc biến mất",
        "slug": "neu_sao_moc_bien_mat",
        "story": "What-if: Sao Mộc — lá chắn hấp dẫn của Hệ Mặt Trời — biến mất.",
        "scenes": [
            ("Nếu Sao Mộc, hành tinh khổng lồ bảo vệ chúng ta, đột nhiên biến mất, Trái Đất sẽ mất đi tấm khiên vô hình suốt bốn tỉ năm.",
             "the giant planet Jupiter fading out of the outer solar system, empty space where it was, cosmic eerie",
             "giant Jupiter slowly fading out of space, stars behind revealed, slow cosmic eerie"),
            ("Lực hấp dẫn khổng lồ của nó từng hút và bẻ hướng vô số sao chổi, tiểu hành tinh ra xa Trái Đất.",
             "comets and asteroids drifting freely through the solar system, no longer deflected, cosmic",
             "comets and asteroids drifting freely through dark space, slow cosmic ominous"),
            ("Không còn lá chắn ấy, hàng loạt thiên thể bắt đầu lao thẳng vào vùng trong của Hệ Mặt Trời.",
             "a swarm of asteroids and comets streaming inward toward the inner solar system, dramatic cosmic",
             "a swarm of asteroids streaming inward toward the sun, slow cosmic dramatic"),
            ("Quỹ đạo các hành tinh dần nhiễu loạn khi mất đi trọng lực neo giữ của gã khổng lồ.",
             "inner planets drifting subtly off their orbital paths without Jupiter, cosmic dramatic",
             "planets drifting slightly off their orbital paths, slow cosmic subtle dramatic"),
            ("Bầu trời đêm Trái Đất ngày càng dày đặc những vệt sao băng và mối đe doạ va chạm.",
             "Earth's night sky filled with streaking meteors and a distant approaching asteroid, ominous beautiful",
             "a night sky filling with streaking meteors over a landscape, slow ominous beautiful"),
            ("Xác suất một cú va chạm huỷ diệt với Trái Đất tăng vọt, chỉ còn là vấn đề thời gian.",
             "a large asteroid looming closer to Earth in dark space, ominous cosmic dramatic",
             "a large asteroid slowly looming closer to Earth, slow cosmic ominous dread"),
            ("Gã khổng lồ thầm lặng nơi rìa Hệ Mặt Trời hoá ra đã âm thầm che chở sự sống suốt hàng tỉ năm.",
             "empty space where Jupiter once was, with a small distant Earth, lonely cosmic haunting",
             "a lonely small Earth in space with empty space where Jupiter was, slow zoom out, haunting"),
        ],
    },
    "day17": {
        "title": "Nếu Trái Đất to gấp đôi",
        "slug": "neu_trai_dat_to_gap_doi",
        "story": "What-if: Trái Đất to gấp đôi → trọng lực tăng vọt.",
        "scenes": [
            ("Nếu Trái Đất đột nhiên to gấp đôi, mọi thứ trên hành tinh sẽ trở nên nặng nề đến mức khó tin.",
             "a dramatically enlarged Earth in space, vast curved horizon, cosmic awe dramatic scale",
             "an enlarged Earth slowly rotating in space, vast curved horizon, slow cosmic awe"),
            ("Trọng lực bề mặt tăng vọt, cơ thể bạn bỗng nặng gấp đôi, mỗi bước đi như mang theo cả tạ.",
             "a person struggling under crushing heavy gravity on a city street, strained posture, dramatic light",
             "a person moving slowly and heavily under crushing gravity on a street, strained, slow dramatic"),
            ("Xương và cơ con người không chịu nổi sức nặng, chỉ đứng thẳng thôi cũng là một cực hình.",
             "a person buckling and struggling under crushing heavy gravity on a city street, body strained low to the ground, oppressive dramatic light",
             "a person slowly buckling under crushing gravity on a city street, strained low, oppressive, slow dramatic"),
            ("Những toà nhà cao tầng và cầu vốn thiết kế cho trọng lực cũ bắt đầu rạn nứt rồi sụp đổ.",
             "tall buildings and bridges cracking and buckling under doubled gravity, structural collapse, dramatic",
             "tall buildings cracking and buckling, debris beginning to fall, slow dramatic"),
            ("Bầu khí quyển bị nén dày đặc hơn, bầu trời chuyển sang một màu lạ lùng chưa từng thấy.",
             "a strangely colored dense sky over a heavy oppressive landscape, thick atmosphere, surreal",
             "a strangely colored dense sky slowly shifting over an oppressive landscape, surreal slow"),
            ("Chim chóc không thể bay nổi, mọi loài sống vật lộn để di chuyển dưới sức hút khủng khiếp.",
             "birds grounded and an animal struggling to move in a heavy-gravity landscape, bleak dramatic",
             "birds grounded and an animal struggling to move slowly, heavy oppressive, slow bleak"),
            ("Hoá ra kích thước của một hành tinh quyết định liệu sự sống có thể tồn tại hay không.",
             "the enlarged Earth seen from space, oppressive and lifeless looking, haunting cosmic",
             "the enlarged Earth slowly rotating in space, oppressive lifeless look, slow zoom out, haunting"),
        ],
    },
    "day18": {
        "title": "Nếu siêu núi lửa Yellowstone thức giấc",
        "slug": "neu_sieu_nui_lua_yellowstone",
        "story": "What-if: siêu núi lửa Yellowstone phun trào.",
        "scenes": [
            ("Nếu siêu núi lửa Yellowstone đang ngủ dưới lòng nước Mỹ bất ngờ thức giấc, hậu quả sẽ vượt xa mọi thảm hoạ từng biết.",
             "a vast volcanic caldera beginning to erupt with a massive eruption column, apocalyptic dramatic",
             "a massive eruption column slowly rising from a vast caldera, smoke billowing, apocalyptic slow"),
            ("Một vụ phun trào lớn gấp hàng ngàn lần núi lửa thường, phun hàng nghìn cây số khối tro lên trời.",
             "a colossal volcanic eruption column towering miles into the sky, immense ash plume, epic dramatic",
             "a colossal ash column towering into the sky, billowing upward, epic dramatic slow"),
            ("Tro bụi phủ kín gần như toàn bộ một châu lục chỉ trong vài ngày, chôn vùi các thành phố.",
             "a city buried under thick grey volcanic ash, ash-covered streets and rooftops, bleak desolate",
             "thick grey ash falling over a buried city, slow drift, bleak desolate"),
            ("Đám mây tro khổng lồ lan ra toàn cầu, che khuất Mặt Trời và đẩy nhiệt độ lao dốc.",
             "a vast ash cloud spreading across the sky blocking the sun, darkened world, ominous cosmic",
             "a vast ash cloud spreading across a darkened sky, the sun dimming, ominous slow"),
            ("Mùa đông núi lửa kéo dài nhiều năm, mùa màng chết, cây cối tàn lụi khắp các châu lục.",
             "dead frozen grey crop fields under an ashen sunless sky, volcanic winter, bleak desolate",
             "slow pan over dead grey crop fields under an ashen sky, faint ash falling, bleak"),
            ("Nạn đói toàn cầu bùng phát khi nguồn lương thực sụp đổ dưới bầu trời không còn ánh nắng.",
             "desperate people in a grey ash-covered wasteland under a sunless sky, grim survival",
             "people trudging through a grey ashen wasteland, slow, grim sunless"),
            ("Một quả bom hẹn giờ khổng lồ vẫn đang lặng lẽ ngủ yên ngay dưới chân chúng ta.",
             "a quiet volcanic caldera landscape with faint steam rising, deceptively calm, ominous",
             "a calm caldera landscape with faint steam rising, deceptively peaceful, slow ominous"),
        ],
    },
    "day19": {
        "title": "Nếu Trái Đất có hai Mặt Trời",
        "slug": "neu_hai_mat_troi",
        "story": "What-if: Trái Đất nằm trong hệ sao đôi, có hai Mặt Trời.",
        "scenes": [
            ("Nếu Trái Đất quay quanh hai Mặt Trời như trong phim viễn tưởng, bầu trời của chúng ta sẽ không bao giờ còn thật sự tối.",
             "two suns hanging in the sky over a landscape, double sunlight, surreal sci-fi dramatic",
             "two suns slowly hanging in the sky over a landscape, double light, surreal slow"),
            ("Ban đêm gần như biến mất, vì luôn có ít nhất một Mặt Trời chiếu sáng bầu trời.",
             "a landscape under perpetual daylight with two suns, no true night, bright surreal",
             "a landscape bathed in perpetual double sunlight, slow drift, bright surreal"),
            ("Nhiệt độ bề mặt tăng vọt, những vùng đất rộng lớn khô cằn dưới ánh nắng gấp đôi.",
             "a cracked sun-scorched desert under two blazing suns, heat haze, bleak dramatic",
             "heat haze rippling over a cracked desert under two suns, slow bleak"),
            ("Quỹ đạo Trái Đất trở nên bất ổn định, lúc quá gần thì thiêu đốt, lúc quá xa thì lạnh giá.",
             "Earth on an erratic orbit between two suns, cosmic view, dramatic unstable",
             "Earth drifting on an erratic path between two suns, slow cosmic unstable dramatic"),
            ("Đại dương bốc hơi dữ dội, những cơn bão khổng lồ liên tục càn quét khắp hành tinh.",
             "giant storm systems swirling over a hot ocean planet under two suns, epic dramatic",
             "giant storm clouds swirling over a hot ocean under two suns, slow epic dramatic"),
            ("Sự sống chỉ còn bám trụ ở những vùng chạng vạng hiếm hoi, nơi ánh nắng dịu hơn.",
             "a narrow habitable twilight zone between scorched land and storm under two suns, atmospheric",
             "a narrow twilight zone with a small settlement between scorched land and storm, slow"),
            ("Hoá ra bóng tối của màn đêm cũng là một món quà quý giá mà ta luôn xem thường.",
             "a dim landscape with two faint suns low on the horizon, symbolizing lost night, haunting",
             "a dim landscape with two faint suns on the horizon, slow, haunting"),
        ],
    },
    "day20": {
        "title": "Nếu toàn bộ băng trên Trái Đất tan hết",
        "slug": "neu_bang_tan_het",
        "story": "What-if: toàn bộ băng hai cực và trên núi tan chảy.",
        "scenes": [
            ("Nếu toàn bộ băng ở hai cực và trên núi tan chảy hết, bản đồ thế giới sẽ phải vẽ lại hoàn toàn.",
             "polar ice caps melting into the ocean, view of Earth from space, blue meltwater, dramatic cosmic",
             "polar ice slowly melting into the ocean, meltwater spreading, slow cosmic dramatic"),
            ("Mực nước biển dâng thêm khoảng bảy mươi mét, nhấn chìm vô số thành phố ven biển.",
             "a coastal city submerged to its rooftops under risen sea, only towers above water, dramatic",
             "slow aerial over a city submerged to its rooftops, calm risen sea, eerie"),
            ("Những vùng đất đông dân nhất hành tinh dần biến mất dưới làn nước mặn mênh mông.",
             "a vast flooded plain where megacities once stood, endless water, surreal desolate",
             "slow aerial over an endless flooded plain where cities once stood, surreal desolate"),
            ("Dòng hải lưu và khí hậu toàn cầu đảo lộn khi lượng nước ngọt khổng lồ đổ vào đại dương.",
             "chaotic ocean currents and storm systems over a flooded Earth, climate chaos, dramatic",
             "swirling storm systems over a flooded ocean world, slow dramatic"),
            ("Hai vùng cực lộ ra những vùng đất mới, trong khi xích đạo nóng đến mức khó sống.",
             "newly exposed bleak land at a former polar region under a pale sky, atmospheric",
             "slow pan over newly exposed bleak polar land under a pale sky, atmospheric"),
            ("Hàng tỉ người buộc phải di cư lên vùng cao, tranh giành phần đất khô ít ỏi còn lại.",
             "huge crowds migrating uphill to highlands above a flooded world, grim dramatic sky",
             "a vast crowd migrating uphill away from rising water, grim slow"),
            ("Lớp băng tưởng chừng vô hại hoá ra đang giữ cho cả bản đồ thế giới đứng yên.",
             "a half-drowned Earth from space, expanded oceans and shrunken land, haunting cosmic",
             "Earth from space with expanded oceans and shrunken land, slow zoom out, haunting"),
        ],
    },
    "day21": {
        "title": "Nếu một tiểu hành tinh khổng lồ đâm Trái Đất",
        "slug": "neu_tieu_hanh_tinh_dam",
        "story": "What-if: tiểu hành tinh khổng lồ va chạm Trái Đất (như thời khủng long).",
        "scenes": [
            ("Nếu một tiểu hành tinh khổng lồ như thứ từng xoá sổ khủng long lao thẳng vào Trái Đất, chỉ vài giây là đủ thay đổi tất cả.",
             "a giant asteroid hurtling toward Earth through space, glowing trail, cosmic ominous dramatic",
             "a giant asteroid hurtling toward Earth, glowing trail, slow cosmic ominous"),
            ("Cú va chạm tạo ra một hố sâu khổng lồ và sóng xung kích quét sạch mọi thứ xung quanh.",
             "a colossal impact crater with a shockwave blast spreading across a landscape, apocalyptic dramatic",
             "a shockwave blast spreading from a colossal impact crater, dust expanding, apocalyptic slow"),
            ("Sóng thần cao hàng trăm mét và những trận cháy khổng lồ lan ra khắp các châu lục.",
             "a towering tsunami and distant firestorms engulfing a coastline, apocalyptic dramatic",
             "a towering wall of water and distant firestorm surging toward a coastline, slow apocalyptic"),
            ("Bụi và tro bắn lên tầng cao khí quyển, che khuất Mặt Trời và gây ra mùa đông va chạm.",
             "a dark dust-choked sky blotting out the sun over a scorched world, impact winter, bleak",
             "a dark dust-filled sky slowly blotting out the sun over a scorched world, bleak slow"),
            ("Trong bóng tối lạnh giá kéo dài, cây cối chết và chuỗi thức ăn toàn cầu sụp đổ.",
             "a cold dark dead forest under a sunless dust sky, collapsed ecosystem, bleak desolate",
             "slow drift over a cold dead forest under a dark dust sky, bleak desolate"),
            ("Chỉ những loài nhỏ bé trú ẩn sâu trong lòng đất mới có cơ hội sống sót qua thảm hoạ.",
             "small creatures sheltering in a dark underground burrow, faint light, grim survival",
             "small creatures in a dark underground burrow, faint light, slow grim"),
            ("Thứ từng kết liễu loài khủng long vẫn đang lặng lẽ rình rập đâu đó ngoài không gian.",
             "a distant asteroid drifting silently in dark space near Earth, ominous cosmic haunting",
             "a distant asteroid drifting silently in space near Earth, slow, ominous haunting"),
        ],
    },
}
