"""What If VN — week 5+6 content data (day29-day42), 14 new science-horror topics.
Merged into DAYS by whatif_produce. Schema matches other weeks:
DAYS[dayN] = {title, slug, story, scenes=[(narrator_vn, image_prompt_en, motion_prompt_en) x7]}
7-scene arc: hook -> immediate -> escalate1 -> escalate2 -> climax -> humanity -> haunting end.
"""

DAYS = {
    "day29": {
        "title": "Nếu Mặt Trăng biến mất", "slug": "neu_mat_trang_bien_mat",
        "story": "the moon vanishes from the sky",
        "scenes": [
            ("Nếu một sáng thức dậy Mặt Trăng biến mất khỏi bầu trời, thứ đầu tiên sụp đổ là nhịp thuỷ triều của đại dương.",
             "a night sky with an empty void where the moon should be, calm dark ocean below, eerie starlight", "slow pan across an empty moonless night sky over a dark ocean, eerie"),
            ("Ngay trong ngày, thuỷ triều gần như biến mất, các vùng bờ biển trở nên tĩnh lặng một cách bất thường.",
             "a deserted coastline with unnaturally still flat water, grey overcast, lonely", "gentle push-in on an unnaturally still flat coastline, grey light"),
            ("Vài tuần sau, mất lực kéo của Mặt Trăng, trục quay Trái Đất bắt đầu lảo đảo nhẹ nhưng đầy nguy hiểm.",
             "Earth from space with a subtly tilted wobbling axis, dramatic cosmic light", "slow rotating view of Earth from space, subtle wobble, dramatic"),
            ("Khí hậu hỗn loạn dần, mùa màng đảo lộn, những loài sống theo ánh trăng mất phương hướng và lụi tàn.",
             "withering crops and disoriented wildlife under a strange dim sky, desaturated somber", "slow drift over withering fields under a strange dim sky, somber"),
            ("Đêm trở nên đen kịt như mực, không còn ánh trăng dẫn đường, chỉ còn những vì sao lạnh lẽo xa xôi.",
             "a pitch-black landscape under only faint distant stars, profound darkness, cold", "slow pan across a pitch-black starlit landscape, cold darkness"),
            ("Con người mất đi người bạn đồng hành bốn tỉ năm, và nhận ra Mặt Trăng từng âm thầm giữ ổn định cho cả hành tinh.",
             "a lone human silhouette looking up at an empty dark sky, melancholic vast", "slow push-in on a lone silhouette gazing at an empty dark sky"),
            ("Không có Mặt Trăng, Trái Đất vẫn quay, nhưng đã đánh mất nhịp điệu từng khiến sự sống nảy nở.",
             "Earth alone in dark space without its moon, silent and vast, ominous", "slow zoom out from a moonless Earth in silent dark space"),
        ],
    },
    "day30": {
        "title": "Nếu tốc độ ánh sáng chậm lại", "slug": "neu_anh_sang_cham_lai",
        "story": "the speed of light slows down",
        "scenes": [
            ("Nếu tốc độ ánh sáng đột nhiên chậm lại, mọi định luật vật lý giữ vũ trụ vận hành bắt đầu rạn nứt.",
             "a surreal sky with light visibly lagging and streaking, distorted glowing horizon", "slow surreal streaks of lagging light across a distorted glowing sky"),
            ("Ngay lập tức, ánh sáng Mặt Trời tới Trái Đất trễ hơn, bầu trời nhập nhoạng một thứ ánh sáng kỳ lạ.",
             "a city under strange dim delayed sunlight, eerie golden haze, surreal", "gentle push-in on a city under eerie delayed dim sunlight, surreal haze"),
            ("Phản ứng hạt nhân trong lòng Mặt Trời thay đổi, năng lượng giải phóng trở nên thất thường và nguy hiểm.",
             "the sun with unstable flickering surface, dramatic solar flares, cosmic", "slow churning unstable solar surface with flickering flares, dramatic"),
            ("Điện, viễn thông và mọi thiết bị dựa trên ánh sáng đồng loạt trục trặc, thế giới chìm vào hỗn loạn.",
             "a dark city with failing flickering lights and dead screens, chaotic dim", "slow drift over a dark city with flickering failing lights"),
            ("Năng lượng liên kết nguyên tử suy yếu, vật chất quanh ta bắt đầu mất đi sự bền vững vốn có.",
             "solid structures subtly shimmering and destabilizing, surreal eerie glow", "slow push-in on shimmering destabilizing structures, surreal"),
            ("Con người nhận ra ánh sáng không chỉ để nhìn, mà là sợi chỉ vô hình dệt nên toàn bộ thực tại.",
             "a lone figure reaching toward distorted shimmering light, awe and dread", "slow push-in on a figure reaching toward distorted shimmering light"),
            ("Khi ánh sáng chậm lại, vũ trụ không sụp đổ trong tiếng nổ, mà tan rã trong sự tĩnh lặng kỳ lạ.",
             "a fading distorted cosmos dissolving into strange silence, vast ominous", "slow zoom out from a fading distorted cosmos dissolving into silence"),
        ],
    },
    "day31": {
        "title": "Nếu Trái Đất mất một nửa khối lượng", "slug": "neu_trai_dat_mat_nua_khoi_luong",
        "story": "Earth loses half its mass",
        "scenes": [
            ("Nếu Trái Đất đột nhiên mất một nửa khối lượng, trọng lực yếu đi và mọi thứ trở nên nhẹ bẫng đáng sợ.",
             "objects and people floating slightly upward on a city street, surreal weak gravity", "gentle slow upward drift of objects on a city street, surreal"),
            ("Ngay lập tức, bước chân hoá thành những cú nhảy dài, nhưng niềm vui nhanh chóng nhường chỗ cho hoảng loạn.",
             "people leaping unnaturally high in a plaza, dust rising, chaotic surreal", "slow motion of figures leaping unnaturally high, dust drifting up"),
            ("Trọng lực yếu không còn giữ nổi khí quyển, lớp không khí bảo vệ bắt đầu rò rỉ ra ngoài vũ trụ.",
             "Earth from space with its atmosphere wisping away into the void, dramatic", "slow view of Earth's atmosphere wisping away into dark space"),
            ("Quỹ đạo quanh Mặt Trời thay đổi, Trái Đất trôi dạt xa dần, khí hậu lạnh đi từng ngày.",
             "Earth drifting along an altered orbit away from a distant sun, cold cosmic", "slow drift of Earth moving away from a distant shrinking sun"),
            ("Đại dương sôi trào rồi bốc hơi trong áp suất sụt giảm, để lại những lòng biển trống hoác.",
             "oceans evaporating into thin mist leaving vast empty basins, desolate", "slow drift over evaporating oceans and emptying sea basins, desolate"),
            ("Con người bám víu mặt đất đang mỏng manh, hiểu ra khối lượng Trái Đất chính là chiếc neo giữ sự sống.",
             "a lone figure clinging to cracked ground under a thinning sky, dread", "slow push-in on a figure clinging to cracked ground, thinning sky"),
            ("Nhẹ hơn không có nghĩa là tự do, một Trái Đất hao gầy là một Trái Đất đang hấp hối.",
             "a shrunken pale Earth drifting alone in cold space, ominous vast", "slow zoom out from a pale shrunken Earth drifting in cold space"),
        ],
    },
    "day32": {
        "title": "Nếu bầu trời đêm không còn ngôi sao", "slug": "neu_bau_troi_khong_sao",
        "story": "the night sky has no stars",
        "scenes": [
            ("Nếu một đêm bạn ngước lên và bầu trời trống rỗng, không một ngôi sao, đó là dấu hiệu vũ trụ đang xa rời ta.",
             "a person looking up at a completely empty black starless night sky, lonely vast", "slow push-in on a figure under a completely empty black sky"),
            ("Vũ trụ giãn nở ngày càng nhanh, kéo các thiên hà ra xa khỏi tầm nhìn của chúng ta mãi mãi.",
             "distant galaxies drifting away into expanding darkness, cosmic lonely", "slow drift of distant galaxies receding into expanding darkness"),
            ("Ánh sáng từ các vì sao xa không còn đủ sức vượt khoảng cách giãn nở để chạm tới Trái Đất.",
             "starlight stretching and fading across an expanding void, eerie cosmic", "slow stretching fading starlight across an expanding void"),
            ("Bầu trời đêm hoá thành một tấm màn đen tuyệt đối, nhân loại bị bỏ lại trong cô độc vũ trụ.",
             "Earth under an absolute black void sky, profound isolation, somber", "slow pan across Earth under an absolute black void sky"),
            ("Không còn các vì sao để định hướng hay mơ mộng, con người mất đi tấm bản đồ cổ xưa nhất của mình.",
             "an old observatory pointing at an empty black sky, melancholic abandoned", "slow push-in on an observatory aimed at an empty black sky"),
            ("Loài người chợt hiểu mình từng may mắn đến nhường nào khi được sinh ra dưới một bầu trời đầy sao.",
             "a lone silhouette remembering stars under an empty sky, wistful vast", "slow push-in on a lone silhouette under an empty wistful sky"),
            ("Một vũ trụ không sao không nổ tung, nó chỉ lặng lẽ nguội lạnh và chìm vào bóng tối vĩnh hằng.",
             "a cold dark cosmos fading into eternal black silence, ominous vast", "slow zoom out into a cold dark cosmos fading to eternal black"),
        ],
    },
    "day33": {
        "title": "Nếu mọi vi khuẩn biến mất", "slug": "neu_vi_khuan_bien_mat",
        "story": "all bacteria vanish",
        "scenes": [
            ("Nếu mọi vi khuẩn trên Trái Đất biến mất trong một giây, sự sụp đổ bắt đầu âm thầm từ những thứ nhỏ bé nhất.",
             "a microscopic world going silent and empty, eerie sterile glow", "slow drift through a sterile empty microscopic world, eerie"),
            ("Ngay lập tức, quá trình phân huỷ ngừng lại, xác lá và sinh vật chết chất đống không thể tan biến.",
             "a forest floor piled with undecaying dead leaves and matter, unsettling", "slow drift over a forest floor piled with undecaying matter"),
            ("Hệ tiêu hoá của muôn loài tê liệt, động vật và con người không còn hấp thụ được thức ăn.",
             "withering livestock in a barren field under grey sky, somber desolate", "slow drift over withering livestock in a barren grey field"),
            ("Đất đai mất đi vi sinh vật, cây trồng héo úa, chuỗi thức ăn của cả hành tinh rạn vỡ từng mắt xích.",
             "dying crops in cracked lifeless soil under a pale sky, desolate", "slow push-in over dying crops in cracked lifeless soil"),
            ("Nạn đói lan khắp các châu lục, một thế giới sạch bóng vi khuẩn lại là một thế giới đang chết dần.",
             "empty famine-struck streets under a barren sky, bleak somber", "slow drift through empty famine-struck streets, bleak"),
            ("Con người nhận ra kẻ thù vô hình bấy lâu thật ra là những người bạn thầm lặng giữ ta sống.",
             "a lone scientist staring at an empty petri dish, melancholic dread", "slow push-in on a lone figure holding an empty petri dish"),
            ("Đôi khi thứ nhỏ bé nhất lại nâng đỡ cả thế giới, và mất chúng là mất tất cả.",
             "a silent lifeless landscape under a pale empty sky, ominous still", "slow zoom out over a silent lifeless landscape, ominous"),
        ],
    },
    "day34": {
        "title": "Nếu Trái Đất có vành đai như Sao Thổ", "slug": "neu_trai_dat_co_vanh_dai",
        "story": "Earth has rings like Saturn",
        "scenes": [
            ("Nếu Trái Đất có vành đai như Sao Thổ, bầu trời sẽ đẹp đến nghẹt thở, nhưng cái giá phải trả không hề nhỏ.",
             "a vast glowing ring arcing across Earth's daytime sky over a city, breathtaking", "slow pan across a vast glowing ring arcing over a city sky"),
            ("Ban ngày, một dải sáng khổng lồ vắt ngang bầu trời, lung linh như cầu vồng bằng băng và đá.",
             "a giant shimmering ice-and-rock ring stretching across a blue sky, majestic", "slow drift along a shimmering ice-and-rock ring across the sky"),
            ("Nhưng bóng của vành đai phủ lên mặt đất, tạo ra những vùng lạnh giá kéo dài nhiều tháng.",
             "a landscape half in the cold shadow of the ring, dramatic contrast", "slow pan over a landscape half in the cold shadow of the ring"),
            ("Vệ tinh và tàu vũ trụ khó lòng vượt qua, nhân loại gần như bị giam dưới chiếc lồng ánh sáng của mình.",
             "satellites trapped near a debris ring around Earth, cosmic dramatic", "slow view of satellites drifting near a debris ring around Earth"),
            ("Đêm xuống, vành đai phản chiếu ánh Mặt Trời, biến bóng tối thành một thứ hoàng hôn không bao giờ tắt.",
             "a night landscape glowing under a luminous reflecting ring, surreal beautiful", "slow pan over a night landscape glowing under a luminous ring"),
            ("Con người sống dưới vẻ đẹp choáng ngợp ấy, vừa ngưỡng mộ vừa sợ hãi sức mạnh của tự nhiên.",
             "a silhouette gazing up at the glowing ring with awe, vast cinematic", "slow push-in on a silhouette gazing up at the glowing ring"),
            ("Một chiếc vương miện rực rỡ cho hành tinh, nhưng vương miện nào cũng nặng trĩu trên đầu kẻ đeo nó.",
             "Earth wearing a brilliant glowing ring in space, majestic ominous", "slow zoom out from Earth wearing a brilliant glowing ring in space"),
        ],
    },
    "day35": {
        "title": "Nếu siêu tân tinh nổ gần Trái Đất", "slug": "neu_sieu_tan_tinh_no_gan",
        "story": "a supernova explodes near Earth",
        "scenes": [
            ("Nếu một ngôi sao gần đó phát nổ thành siêu tân tinh, ánh sáng chói loà sẽ là dấu hiệu báo tử tuyệt đẹp.",
             "a blindingly bright exploding star dominating the night sky over Earth, epic", "slow intensifying glow of an exploding star over the night sky"),
            ("Trong nhiều ngày, bầu trời đêm sáng như ban ngày, một quả cầu lửa lơ lửng giữa các vì sao.",
             "a brilliant fireball star lighting the night sky as bright as day, surreal", "slow pan across a brilliant fireball lighting the night like day"),
            ("Rồi luồng bức xạ gamma ập tới, xé toạc tầng ozone bảo vệ sự sống của Trái Đất.",
             "invisible radiation striking Earth's atmosphere, shimmering damaged sky, dramatic", "slow shimmering distortion striking the upper atmosphere, dramatic"),
            ("Không còn lá chắn ozone, tia cực tím thiêu đốt cây cối, đại dương và mọi sinh vật phơi mình.",
             "scorched landscapes and bleached oceans under a harsh sky, desolate", "slow drift over scorched bleached landscapes under a harsh sky"),
            ("Chuỗi thức ăn sụp đổ từ những sinh vật nhỏ nhất, một làn sóng tuyệt chủng lặng lẽ lan rộng.",
             "a dying ecosystem under a pale irradiated sky, bleak somber", "slow push-in over a dying ecosystem under a pale sky"),
            ("Con người ẩn mình dưới lòng đất, nhìn lên bầu trời từng rực rỡ giờ hoá thành bản án tử.",
             "people sheltering underground looking up at a glowing sky, dread", "slow push-in on figures sheltering underground, glowing sky above"),
            ("Cái chết của một ngôi sao xa xôi cũng đủ kết liễu sự sống trên một hành tinh non trẻ.",
             "Earth scorched and silent under the fading supernova glow, ominous", "slow zoom out from a scorched silent Earth under fading glow"),
        ],
    },
    "day36": {
        "title": "Nếu Trái Đất rơi vào Mặt Trời", "slug": "neu_trai_dat_roi_vao_mat_troi",
        "story": "Earth falls into the sun",
        "scenes": [
            ("Nếu Trái Đất mất quỹ đạo và bắt đầu rơi về phía Mặt Trời, đồng hồ đếm ngược cho sự sống lập tức khởi động.",
             "Earth slowly drifting toward a huge glowing sun in space, ominous epic", "slow drift of Earth edging toward a huge glowing sun"),
            ("Những tuần đầu, Mặt Trời mỗi ngày một lớn hơn trên bầu trời, nhiệt độ tăng lên không ngừng.",
             "a swollen sun looming larger over a hot hazy horizon, dramatic", "slow looming of a swollen sun over a hot hazy horizon"),
            ("Đại dương bắt đầu sôi và bốc hơi, những thành phố ven biển chìm trong hơi nóng nghẹt thở.",
             "coastal cities under boiling steaming seas and scorching sky, apocalyptic", "slow drift over steaming boiling seas beside scorched cities"),
            ("Khi tới gần hơn, đất đá nứt nẻ và nóng chảy, hành tinh xanh hoá thành một quả cầu lửa.",
             "a cracked landscape glowing with molten rivers under a giant sun, hellish", "slow push-in over a cracked landscape with glowing molten rivers"),
            ("Bầu khí quyển bị thổi bay, không còn gì che chở Trái Đất khỏi cơn thịnh nộ của ngôi sao mẹ.",
             "Earth's atmosphere torn away near a blazing sun, dramatic cosmic", "slow view of Earth's atmosphere stripped away near a blazing sun"),
            ("Con người chứng kiến những khoảnh khắc cuối cùng, nhỏ bé trước sức mạnh đã từng nuôi dưỡng mình.",
             "a lone silhouette before an overwhelming blazing sun, awe and dread", "slow push-in on a silhouette before an overwhelming blazing sun"),
            ("Trái Đất tan biến vào Mặt Trời không một tiếng vọng, ngôi nhà của ta trở về với ngọn lửa sinh ra nó.",
             "Earth dissolving into the blazing surface of the sun, ominous epic", "slow zoom into Earth dissolving onto the blazing sun's surface"),
        ],
    },
    "day37": {
        "title": "Nếu Mặt Trời tắt trong một năm", "slug": "neu_mat_troi_tat_1_nam",
        "story": "the sun goes dark for one year",
        "scenes": [
            ("Nếu Mặt Trời tắt nắng suốt một năm, bóng tối và giá lạnh sẽ siết chặt Trái Đất từng ngày một.",
             "a dim city under a darkened sun and cold grey light, bleak", "slow pan across a dim city under a darkened cold sun"),
            ("Chỉ sau một tuần, nhiệt độ toàn cầu lao dốc, sương giá phủ trắng cả những vùng nhiệt đới.",
             "frost spreading over a tropical city street, unnatural cold, somber", "slow creep of frost spreading over a tropical street"),
            ("Quang hợp ngừng lại, cây cối lụi tàn, chuỗi thức ăn của cả hành tinh bắt đầu rạn vỡ.",
             "withered frozen forests under a dark sky, desolate cold", "slow drift over withered frozen forests under a dark sky"),
            ("Đại dương đóng băng từ bề mặt, các thành phố chìm trong tuyết và bóng tối triền miên.",
             "a frozen city buried in snow under perpetual darkness, bleak", "slow drift over a frozen snow-buried city in darkness"),
            ("Con người co cụm quanh những nguồn nhiệt ít ỏi, chiến đấu với cái lạnh để giành giật sự sống.",
             "people huddled around fires in a dark frozen shelter, somber warm glow", "slow push-in on people huddled around fires in the dark"),
            ("Một năm không Mặt Trời dạy nhân loại rằng ánh nắng tưởng chừng hiển nhiên lại là phép màu nuôi sống tất cả.",
             "a lone figure waiting for sunrise on a frozen horizon, hopeful melancholic", "slow push-in on a figure waiting on a frozen horizon"),
            ("Khi Mặt Trời trở lại, thế giới đã đổi thay mãi mãi, biết ơn từng tia nắng từng xem là điều nhỏ nhặt.",
             "first faint sunlight returning over a frozen thawing world, hopeful", "slow brightening of faint sunlight over a thawing frozen world"),
        ],
    },
    "day38": {
        "title": "Nếu toàn bộ cây xanh chết", "slug": "neu_toan_bo_cay_xanh_chet",
        "story": "all plants die",
        "scenes": [
            ("Nếu toàn bộ cây xanh trên Trái Đất chết đi, đồng hồ oxy của nhân loại bắt đầu đếm ngược.",
             "a barren grey landscape of dead leafless trees under pale sky, desolate", "slow drift over a barren grey landscape of dead trees"),
            ("Ngay lập tức, nguồn cung oxy mới ngừng lại, bầu không khí dần trở nên ngột ngạt khó thở.",
             "a hazy city street with people gasping under thin pale air, somber", "slow push-in on a hazy city street under thin pale air"),
            ("Không còn quang hợp, khí cacbonic tích tụ, hiệu ứng nhà kính đẩy nhiệt độ tăng vọt.",
             "a smoggy overheated city under a sickly yellow sky, oppressive", "slow drift over a smoggy overheated city, oppressive haze"),
            ("Chuỗi thức ăn sụp đổ từ gốc rễ, động vật ăn cỏ chết đói, kéo theo mọi loài phía trên.",
             "starving wildlife on a cracked barren plain, bleak desolate", "slow drift over starving wildlife on a cracked barren plain"),
            ("Đất đai không còn rễ cây giữ lại, xói mòn và bão bụi nuốt chửng những vùng từng trù phú.",
             "a dust storm swallowing a barren abandoned farmland, apocalyptic", "slow approach of a dust storm over barren abandoned farmland"),
            ("Con người hiểu ra rằng mỗi chiếc lá xanh từng là một hơi thở mà ta nhận miễn phí mỗi ngày.",
             "a lone figure holding a single wilted leaf under a pale sky, melancholic", "slow push-in on a figure holding a single wilted leaf"),
            ("Một hành tinh không màu xanh là một hành tinh nín thở, và hơi thở ấy không kéo dài được lâu.",
             "a grey lifeless Earth from space, oceans dull, ominous vast", "slow zoom out from a grey lifeless Earth in space"),
        ],
    },
    "day39": {
        "title": "Nếu trọng lực mạnh gấp đôi", "slug": "neu_trong_luc_gap_doi",
        "story": "gravity becomes twice as strong",
        "scenes": [
            ("Nếu trọng lực Trái Đất mạnh gấp đôi, mỗi bước đi sẽ nặng như đang vác cả thân mình thứ hai.",
             "people struggling to stand crushed by heavy gravity on a city street, dramatic", "slow push-in on people struggling under crushing heavy gravity"),
            ("Ngay lập tức, cơ thể oằn xuống, nhấc một cánh tay cũng trở thành nỗ lực mệt nhoài.",
             "a person buckling and straining under their own doubled weight, somber", "slow strained movement of a person buckling under heavy weight"),
            ("Tim phải bơm máu vất vả gấp bội, hơi thở nặng nề, sức khoẻ con người suy kiệt nhanh chóng.",
             "an exhausted figure gasping and pinned low to the ground, dramatic", "slow push-in on an exhausted figure pinned low, gasping"),
            ("Những toà nhà cao tầng rạn nứt rồi đổ sụp, không kết cấu nào chịu nổi sức nặng tăng gấp đôi.",
             "skyscrapers cracking and collapsing under their own weight, apocalyptic", "slow collapse of cracking skyscrapers under their own weight"),
            ("Cây cối gãy đổ, núi non lở xuống, cả khí quyển bị nén lại dày đặc và ngột ngạt.",
             "collapsing forests and landslides under a heavy dense sky, chaotic", "slow drift over collapsing forests and landslides, heavy sky"),
            ("Con người bò sát mặt đất, hiểu rằng trọng lực dịu dàng bấy lâu mới là điều cho ta đứng thẳng.",
             "a figure crawling low across cracked ground, dramatic somber", "slow push-in on a figure crawling low across cracked ground"),
            ("Chỉ cần nặng thêm một chút, thế giới quen thuộc đã hoá thành nhà tù vô hình ghì chặt tất cả.",
             "a crushed silent cityscape under an oppressive heavy sky, ominous", "slow zoom out over a crushed silent cityscape, heavy sky"),
        ],
    },
    "day40": {
        "title": "Nếu loài người tiến hoá thêm một triệu năm", "slug": "neu_loai_nguoi_tien_hoa",
        "story": "humans evolve for another million years",
        "scenes": [
            ("Nếu loài người tiến hoá thêm một triệu năm, hình hài và trí tuệ của con cháu ta sẽ khác đến khó nhận ra.",
             "a futuristic evolved human silhouette with subtly altered features, awe cinematic", "slow push-in on a futuristic evolved human silhouette, awe"),
            ("Cơ thể có thể mảnh mai hơn, hộp sọ lớn hơn, đôi mắt thích nghi với ánh sáng nhân tạo.",
             "an evolved human with larger eyes and slender frame in a future city, surreal", "slow reveal of an evolved human with larger eyes, surreal"),
            ("Công nghệ hoà vào cơ thể, ranh giới giữa con người và máy móc dần mờ nhạt rồi tan biến.",
             "a human merged with glowing technology, cybernetic ethereal glow", "slow push-in on a human merged with glowing technology"),
            ("Có thể loài người tách thành nhiều nhánh, kẻ sống trên các vì sao, người ở lại Trái Đất già cỗi.",
             "diverging human forms, one cosmic one earthbound, epic cinematic", "slow drift between two diverging human forms, cosmic and earthbound"),
            ("Ký ức về tổ tiên hôm nay chỉ còn là huyền thoại mờ ảo trong tâm trí những hậu duệ xa xôi.",
             "a future being looking at ancient human relics in a museum, wistful", "slow push-in on a future being studying ancient human relics"),
            ("Con người hiện tại chỉ là một chương ngắn ngủi trong cuốn sách tiến hoá dài vô tận.",
             "a vast timeline of evolving human silhouettes fading into the future, epic", "slow pan along a timeline of evolving human silhouettes"),
            ("Chúng ta sẽ không biến mất, ta chỉ trở thành một điều gì đó hoàn toàn mới, xa lạ và kỳ vĩ.",
             "a radiant evolved humanity among the stars, hopeful awe cosmic", "slow zoom out to a radiant evolved humanity among the stars"),
        ],
    },
    "day41": {
        "title": "Nếu Trái Đất hoá hành tinh băng", "slug": "neu_trai_dat_hanh_tinh_bang",
        "story": "Earth becomes a snowball planet",
        "scenes": [
            ("Nếu Trái Đất đóng băng từ hai cực tới tận xích đạo, một kỷ băng hà toàn cầu sẽ nuốt chửng tất cả.",
             "ice sheets spreading across a frozen continent from the poles, epic cold", "slow drift over ice sheets spreading across a frozen continent"),
            ("Băng giá lan nhanh, đại dương đóng cứng thành những cánh đồng băng mênh mông trắng xoá.",
             "a vast frozen white ocean stretching to the horizon, desolate cold", "slow pan across a vast frozen white ocean to the horizon"),
            ("Các thành phố chìm dưới lớp băng dày, ánh nắng phản chiếu hết khỏi mặt băng càng khiến hành tinh lạnh thêm.",
             "a city buried under thick blue ice under a pale sun, bleak", "slow drift over a city buried under thick blue ice"),
            ("Sự sống co cụm quanh những miệng núi lửa hiếm hoi, nơi hơi ấm cuối cùng còn rỉ ra từ lòng đất.",
             "fragile life clustered around a glowing volcanic vent in ice, somber warm glow", "slow push-in on a glowing volcanic vent amid endless ice"),
            ("Bầu trời trong vắt nhưng lạnh thấu xương, cả hành tinh phủ một màu trắng tang thương bất tận.",
             "an endless white frozen landscape under a clear cold sky, vast bleak", "slow pan across an endless white frozen landscape"),
            ("Con người chiến đấu để giữ ngọn lửa sống sót, biết rằng băng giá này từng nhấn chìm Trái Đất thật sự.",
             "people guarding a small fire in a frozen ruin, somber warm glow", "slow push-in on people guarding a small fire in frozen ruins"),
            ("Một quả cầu tuyết lơ lửng trong không gian, đẹp đến lạnh người, và im lặng đến rợn ngợp.",
             "a white frozen snowball Earth glowing in dark space, beautiful ominous", "slow zoom out from a white frozen snowball Earth in space"),
        ],
    },
    "day42": {
        "title": "Nếu một siêu sóng thần quét toàn cầu", "slug": "neu_sieu_song_than_toan_cau",
        "story": "a mega-tsunami sweeps the globe",
        "scenes": [
            ("Nếu một sườn núi lửa khổng lồ sụp xuống biển, một siêu sóng thần cao ngàn mét sẽ trỗi dậy.",
             "a colossal towering tsunami wave rising over a dark ocean, epic terrifying", "slow rising of a colossal towering wave over a dark ocean"),
            ("Bức tường nước khổng lồ lao về phía bờ với tốc độ của một chiếc máy bay phản lực.",
             "a giant wall of water racing toward a distant coastline, dramatic", "slow approach of a giant wall of water toward a coastline"),
            ("Trong vài giờ, những thành phố ven biển sầm uất biến mất hoàn toàn dưới làn nước cuồng nộ.",
             "a coastal city engulfed and submerged by a massive wave, apocalyptic", "slow engulfing of a coastal city by a massive wave"),
            ("Sóng dội vào các lục địa rồi lan rộng, không bến bờ nào trên thế giới còn an toàn.",
             "flooded continents with submerged landmarks under grey sky, desolate", "slow drift over flooded continents and submerged landmarks"),
            ("Khi nước cuối cùng rút đi, để lại những vùng đất hoang tàn phủ đầy bùn và đổ nát.",
             "a ruined muddy coastline strewn with wreckage after the flood, bleak", "slow drift over a ruined muddy coastline strewn with wreckage"),
            ("Con người sống sót trên những vùng cao, lặng nhìn bản đồ thế giới được vẽ lại bằng nước.",
             "survivors on high ground looking over a flooded world, somber vast", "slow push-in on survivors overlooking a flooded world"),
            ("Đại dương vốn nuôi dưỡng sự sống cũng có thể xoá sổ nó chỉ trong một con sóng duy nhất.",
             "a vast quiet flooded Earth from above, calm ominous", "slow zoom out over a vast quiet flooded Earth from above"),
        ],
    },
}
