"""Content data for 'Nếu... thì sao' WEEK 4 (day22–day28). Same shape as whatif_days.py:
each day = title, slug, story, 7 scenes = (narrator_vn, image_prompt_en, motion_prompt_en).
Motion = camera + atmospheric (animatable from the still). Merged via whatif_produce.py.
"""

DAYS = {
    "day22": {
        "title": "Nếu Trái Đất quay ngược",
        "slug": "neu_trai_dat_quay_nguoc",
        "story": "What-if: Trái Đất quay theo chiều ngược lại.",
        "scenes": [
            ("Nếu Trái Đất đột nhiên quay theo chiều ngược lại, điều đầu tiên bạn nhận ra là Mặt Trời mọc ở hướng tây.",
             "the sun rising over a city skyline from the west, reversed sunrise, surreal warm light",
             "the sun slowly rising over a city skyline, warm reversed sunrise glow, slow surreal"),
            ("Các dòng hải lưu và luồng gió toàn cầu đảo chiều, viết lại hoàn toàn bản đồ khí hậu.",
             "global ocean currents and wind bands reversing direction over Earth from space, dramatic cosmic",
             "ocean currents and cloud bands slowly swirling in reverse over Earth, slow cosmic"),
            ("Những sa mạc khô cằn như Sahara dần được phủ xanh bởi mưa và độ ẩm mới.",
             "a former desert turning green with new vegetation and rain clouds, surreal lush transformation",
             "green vegetation spreading over a former desert under rain clouds, slow lush surreal"),
            ("Trong khi đó, nhiều vùng đất xanh tươi trù phú lại biến thành hoang mạc khô cằn.",
             "a once-green fertile region turning into a dry cracked desert, bleak transformation",
             "slow pan over a fertile region drying into cracked desert, bleak slow"),
            ("Khí hậu toàn cầu bị xáo trộn dữ dội, bão tố và thời tiết cực đoan bùng phát khắp nơi.",
             "extreme storms and chaotic weather over a transformed Earth, dramatic turbulent sky",
             "chaotic storm clouds churning over a transformed landscape, slow dramatic"),
            ("Hệ sinh thái khắp hành tinh phải vật lộn thích nghi, nhiều loài không kịp và biến mất.",
             "animals migrating across a drastically changed landscape struggling to adapt, bleak atmospheric",
             "animals slowly migrating across a changed landscape, slow bleak atmospheric"),
            ("Hoá ra chỉ một chiều quay thôi cũng đủ định hình toàn bộ thế giới mà ta đang sống.",
             "Earth from space rotating in reverse, swapped green and desert regions, haunting cosmic",
             "Earth slowly rotating in reverse in space, swapped regions visible, slow zoom out, haunting"),
        ],
    },
    "day23": {
        "title": "Nếu Mặt Trời mờ đi một nửa",
        "slug": "neu_mat_troi_mo_di",
        "story": "What-if: Mặt Trời giảm còn một nửa độ sáng.",
        "scenes": [
            ("Nếu Mặt Trời đột nhiên mờ đi chỉ còn một nửa độ sáng, ban ngày sẽ trông như một buổi hoàng hôn kéo dài mãi mãi.",
             "a dim half-bright sun over a landscape in perpetual dusk, faded light, eerie atmospheric",
             "a dim sun hanging low over a landscape in perpetual dusk, faded light, slow eerie"),
            ("Nhiệt độ toàn cầu lao dốc nhanh chóng, cái lạnh tràn xuống cả những vùng nhiệt đới.",
             "frost spreading over a once-tropical landscape under a dim sun, cold bleak eerie",
             "frost slowly creeping over a tropical landscape under a dim sun, slow cold bleak"),
            ("Cây cối thiếu ánh sáng để quang hợp, rừng và mùa màng dần héo úa rồi chết.",
             "a withering dying forest under weak dim sunlight, fading leaves, bleak atmospheric",
             "slow pan over a withering forest under weak dim light, leaves drifting, bleak"),
            ("Băng giá lan rộng từ hai cực, một kỷ băng hà mới bao trùm phần lớn hành tinh.",
             "vast ice sheets spreading over a continent under a dim sun, new ice age, bleak cosmic",
             "vast ice slowly spreading across a continent under a dim sun, slow bleak"),
            ("Các thành phố đóng băng dần, con người co cụm quanh những nguồn nhiệt cuối cùng.",
             "a frozen dim city with survivors huddled around fire and heat sources, cold grim",
             "survivors huddled around fire in a frozen dim city, flames flickering, slow grim"),
            ("Sự sống rút về những vùng địa nhiệt và miệng núi lửa, nơi còn chút hơi ấm hiếm hoi.",
             "a small settlement near a glowing geothermal vent in a frozen dim world, faint warm light",
             "a settlement near a glowing geothermal vent in a frozen world, faint warm glow, slow"),
            ("Mỗi tia nắng ta nhận hằng ngày hoá ra mong manh và quý giá hơn ta vẫn tưởng rất nhiều.",
             "a faint dim sun low over a frozen silent world, haunting bleak",
             "a faint dim sun low over a frozen silent world, slow, haunting"),
        ],
    },
    "day24": {
        "title": "Nếu một ngày dài 48 giờ",
        "slug": "neu_ngay_dai_48h",
        "story": "What-if: Trái Đất quay chậm tới mức một ngày dài 48 giờ.",
        "scenes": [
            ("Nếu Trái Đất quay chậm đến mức một ngày kéo dài bốn mươi tám giờ, sự sống sẽ phải đối mặt với những thái cực khắc nghiệt.",
             "a low sun over a landscape with very long stretched shadows, an extremely long day, dramatic",
             "a low sun barely moving over a landscape with long stretched shadows, slow dramatic"),
            ("Ban ngày kéo dài hai mươi bốn giờ liên tục, Mặt Trời thiêu đốt mặt đất không ngừng nghỉ.",
             "a scorched cracked landscape under a relentless unmoving sun, intense heat haze, bleak",
             "heat haze rippling over a scorched landscape under a relentless sun, slow bleak"),
            ("Rồi ban đêm cũng kéo dài hai mươi bốn giờ, cái lạnh cắt da bao trùm mọi thứ trong bóng tối.",
             "a frozen dark landscape under a long cold starry night, bitter cold, bleak eerie",
             "a frozen dark landscape under a long starry night, faint frost forming, slow eerie"),
            ("Biên độ nhiệt giữa ngày và đêm trở nên cực đoan, làm nứt vỡ cả đá và công trình.",
             "cracked rock and crumbling structures from extreme temperature swings, bleak dramatic",
             "slow push-in on cracked rock and crumbling structures, faint dust, bleak"),
            ("Cây cối và động vật vật lộn để sống sót qua chu kỳ nắng nóng và giá lạnh kéo dài.",
             "sparse struggling plants and animals in a harsh landscape between scorching and freezing, bleak",
             "slow pan over sparse struggling plants in a harsh landscape, bleak atmospheric"),
            ("Con người buộc phải sống theo một nhịp sinh học hoàn toàn mới và kỳ lạ.",
             "a human settlement at the boundary of long day and night, half light half dark, atmospheric",
             "a settlement at the boundary of long day and night, slow atmospheric"),
            ("Nhịp quay hai mươi bốn giờ nhỏ bé hoá ra chính là thứ giữ cho sự sống được cân bằng.",
             "Earth from space rotating very slowly, half lit half dark, haunting cosmic",
             "Earth rotating very slowly in space, half lit half dark, slow zoom out, haunting"),
        ],
    },
    "day25": {
        "title": "Nếu bầu khí quyển dày gấp đôi",
        "slug": "neu_khi_quyen_day_gap_doi",
        "story": "What-if: bầu khí quyển Trái Đất dày đặc gấp đôi.",
        "scenes": [
            ("Nếu bầu khí quyển Trái Đất đột nhiên dày đặc gấp đôi, ngay cả việc hít thở và nhìn bầu trời cũng sẽ khác lạ.",
             "a strangely thick hazy colored sky over a landscape, dense atmosphere, surreal heavy",
             "a thick hazy colored sky slowly shifting over a landscape, dense, surreal slow"),
            ("Áp suất không khí tăng vọt đè nặng lên mọi thứ, bầu trời chuyển sang sắc xanh đậm lạ lùng.",
             "a deep blue oppressive thick sky over an oppressed landscape, high pressure, surreal",
             "a deep blue oppressive thick sky over a landscape, faint haze drifting, slow surreal"),
            ("Ánh sáng tán xạ mạnh khiến những buổi hoàng hôn trở nên rực rỡ chưa từng thấy.",
             "an intensely vivid scattered sunset under a thick atmosphere, surreal vivid colors",
             "an intensely vivid sunset glowing under a thick atmosphere, slow surreal"),
            ("Những cơn bão trở nên mạnh hơn nhiều, mang theo sức gió và lượng mưa khủng khiếp.",
             "a massive powerful storm system under a dense heavy sky over a landscape, epic dramatic",
             "a massive storm churning under a dense heavy sky, slow epic dramatic"),
            ("Nhiều loài vật khó thích nghi với áp suất và thành phần không khí mới, dần biến mất.",
             "animals struggling under a heavy dense atmosphere, bleak oppressive landscape, atmospheric",
             "animals moving slowly under a heavy dense sky, oppressive, slow bleak"),
            ("Con người phải học cách sống dưới một bầu trời nặng nề và ngột ngạt hơn bao giờ hết.",
             "a human settlement under a heavy oppressive thick-aired sky, dim atmospheric",
             "a settlement under a heavy oppressive sky, faint haze, slow atmospheric"),
            ("Lớp khí mỏng manh quanh Trái Đất hoá ra đã được cân chỉnh vừa khít cho sự sống.",
             "Earth from space with a visibly thick glowing atmosphere halo, haunting cosmic",
             "Earth from space with a thick glowing atmosphere halo, slow zoom out, haunting"),
        ],
    },
    "day26": {
        "title": "Nếu toàn bộ nước ngọt biến mất",
        "slug": "neu_nuoc_ngot_bien_mat",
        "story": "What-if: toàn bộ nước ngọt trên Trái Đất biến mất.",
        "scenes": [
            ("Nếu toàn bộ nước ngọt trên Trái Đất đột nhiên biến mất, đồng hồ đếm ngược cho sự sống sẽ bắt đầu ngay lập tức.",
             "a dried-up empty river bed and cracked lake, no fresh water, bleak desolate",
             "slow pan over a dried cracked riverbed and empty lake, dust drifting, bleak"),
            ("Sông hồ cạn trơ đáy, những đập nước khổng lồ trở thành thung lũng bụi khô nứt nẻ.",
             "a giant dam holding back only a dry cracked dusty valley, no water, bleak desolate",
             "slow aerial over a dry cracked reservoir behind a giant dam, dust drifting, bleak"),
            ("Cây trồng và gia súc chết hàng loạt chỉ sau vài ngày không còn nước tưới.",
             "withered dead crops and a parched barren farm under a harsh sky, bleak agricultural",
             "slow pan over withered dead crops on a parched farm, dust blowing, bleak"),
            ("Con người tuyệt vọng tranh giành từng giọt nước còn sót lại trong các thành phố khô khát.",
             "desperate crowds gathering around a last trickle of water in a dry city, grim dramatic",
             "desperate crowd around a last water source in a dry city, slow grim"),
            ("Các đô thị sầm uất dần biến thành những hoang mạc bụi bặm không một bóng sống.",
             "a once-busy city turned into a dusty lifeless desert, abandoned streets, bleak desolate",
             "slow aerial over an abandoned dusty city turning to desert, dust drifting, bleak"),
            ("Những dòng người di cư tuyệt vọng kéo nhau đi khắp nơi chỉ để tìm nước.",
             "long lines of refugees crossing a dusty wasteland searching for water, grim dramatic sky",
             "a long line of refugees trekking across a dusty wasteland, slow grim"),
            ("Chỉ ba phần trăm nước ngọt ít ỏi hoá ra đang gánh trên vai cả nền văn minh nhân loại.",
             "a single drop of water over cracked dry earth, macro symbolic, bleak haunting",
             "extreme macro of a single water drop over cracked earth, faint shimmer, slow haunting"),
        ],
    },
    "day27": {
        "title": "Nếu Trái Đất bị khoá thuỷ triều với Mặt Trời",
        "slug": "neu_trai_dat_khoa_thuy_trieu",
        "story": "What-if: Trái Đất luôn quay một mặt về phía Mặt Trời (tidally locked).",
        "scenes": [
            ("Nếu Trái Đất bị khoá thuỷ triều, luôn quay một mặt về phía Mặt Trời, hành tinh sẽ bị chia thành hai thế giới đối lập.",
             "Earth half in eternal day and half in eternal night facing the sun, dramatic cosmic contrast",
             "Earth slowly shown half eternal day half eternal night, dramatic cosmic slow"),
            ("Một nửa hành tinh luôn hướng về Mặt Trời, cháy nắng thiêu đốt không bao giờ ngừng nghỉ.",
             "a scorched cracked desert under a permanently fixed sun, intense heat, bleak",
             "heat haze over a scorched desert under a fixed unmoving sun, slow bleak"),
            ("Nửa còn lại chìm trong đêm tối băng giá vĩnh cửu, không bao giờ thấy ánh nắng.",
             "a frozen dark ice world on the night side under stars, eternal night, bleak eerie",
             "a frozen dark ice landscape under stars, faint frost, slow eerie"),
            ("Giữa hai cực đoan ấy, những cơn bão khủng khiếp gào thét không ngừng dọc theo ranh giới.",
             "a towering wall of storms raging along the day-night terminator line, epic dramatic",
             "a towering storm wall raging along the day-night boundary, lightning, slow epic"),
            ("Sự sống chỉ có thể tồn tại ở dải chạng vạng hẹp nằm giữa lửa và băng.",
             "a narrow twilight habitable strip between scorched land and frozen dark, atmospheric",
             "a narrow twilight strip between fire and ice, faint light, slow atmospheric"),
            ("Loài người buộc phải dồn hết vào dải đất mong manh ấy để sinh tồn.",
             "a human settlement crowded along the narrow twilight zone, dim hopeful atmospheric",
             "a settlement along the narrow twilight zone, dim light, slow atmospheric"),
            ("Vòng ngày và đêm luân phiên mà ta xem là hiển nhiên hoá ra là một món quà vô giá.",
             "tidally locked Earth from space, one bright side one dark side, haunting cosmic",
             "tidally locked Earth in space, bright and dark sides, slow zoom out, haunting"),
        ],
    },
    "day28": {
        "title": "Nếu từ trường Trái Đất đảo cực",
        "slug": "neu_tu_truong_dao_cuc",
        "story": "What-if: từ trường Trái Đất đảo cực (đã xảy ra nhiều lần trong lịch sử).",
        "scenes": [
            ("Nếu từ trường Trái Đất đảo cực, điều từng xảy ra nhiều lần trong lịch sử, cực bắc và cực nam sẽ hoán đổi cho nhau.",
             "Earth's faint magnetic field lines flipping orientation around the planet, cosmic diagram dramatic",
             "Earth's faint magnetic field lines slowly flipping around the planet, slow cosmic"),
            ("Mọi chiếc la bàn trên thế giới bỗng chỉ sai hướng, chim di cư mất phương hướng dẫn đường.",
             "a compass needle pointing wrong and confused migratory birds in a pale sky, eerie atmospheric",
             "a compass needle slowly drifting wrong, confused birds wheeling in the sky, slow eerie"),
            ("Trong quá trình đảo cực, từ trường yếu đi nhiều, để lộ Trái Đất trước bức xạ vũ trụ.",
             "a weakened magnetic field letting cosmic radiation through toward Earth, glowing particles, cosmic",
             "faint cosmic radiation streaming through a weakened field toward Earth, slow cosmic"),
            ("Bức xạ Mặt Trời lọt qua nhiều hơn, gây trục trặc cho vệ tinh và lưới điện toàn cầu.",
             "a satellite glitching in orbit and a city grid flickering under increased radiation, dramatic",
             "a satellite glitching in orbit and a city grid flickering below, slow dramatic"),
            ("Cực quang vốn chỉ có ở hai cực nay xuất hiện rực rỡ ngay cả tại vùng xích đạo.",
             "brilliant auroras over a tropical equatorial city skyline, surreal beautiful ominous",
             "shimmering auroras over a tropical city skyline, slow surreal beautiful"),
            ("Sự sống có thể thích nghi, nhưng giai đoạn chuyển giao kéo dài hàng nghìn năm đầy biến động.",
             "a turbulent transitional Earth under shifting skies, long unstable era, atmospheric dramatic",
             "shifting turbulent skies over a landscape, slow atmospheric dramatic"),
            ("Đây không phải viễn tưởng, mà là điều Trái Đất đã trải qua nhiều lần và sẽ còn lặp lại.",
             "Earth from space with shifting aurora-lit poles, haunting cosmic scientific",
             "Earth from space with aurora-lit shifting poles, slow zoom out, haunting"),
        ],
    },
}
