"""Content data for 'Nếu... thì sao' WEEK 2 (day8–day14). Same shape as whatif_days.py:
each day = title, slug, story, 7 scenes = (narrator_vn, image_prompt_en, motion_prompt_en).
Motion prompts are camera + atmospheric (animatable from the still — avoids Meta's
'couldn't animate' error). Merged into the run via scripts/whatif_produce.py.
"""

DAYS = {
    "day8": {
        "title": "Nếu oxy biến mất 5 giây",
        "slug": "neu_oxy_bien_mat",
        "story": "What-if: toàn bộ oxy trên Trái Đất biến mất trong 5 giây.",
        "scenes": [
            ("Nếu toàn bộ oxy trên Trái Đất biến mất chỉ trong năm giây, bạn sẽ ngất xỉu trước khi kịp nhận ra điều gì đang xảy ra.",
             "a busy city street where everyone has suddenly collapsed unconscious at once, eerie stillness, daytime",
             "slow push-in over a city street where people have just collapsed motionless, papers settling, eerie still air"),
            ("Mọi công trình bê tông vốn cần oxy để kết dính lập tức vụn rã, các toà nhà đổ sập thành bụi.",
             "concrete buildings crumbling into dust simultaneously across a city skyline, collapse, dramatic",
             "city buildings crumbling into dust, debris cascading down, dust rising, slow dramatic"),
            ("Bầu trời chuyển tối sầm vì không còn oxy tán xạ ánh sáng, ban ngày hoá thành chạng vạng kỳ lạ.",
             "a city under a strangely darkened daytime sky, dim eerie twilight at noon, surreal",
             "a darkened daytime sky slowly dimming over a silent city, eerie surreal, slow"),
            ("Mọi ngọn lửa, động cơ và máy bay đang bay đều tắt ngấm cùng lúc, rơi xuống trong im lặng.",
             "an airplane gliding down silently from a darkening sky over a landscape, engines dead, dramatic",
             "a plane gliding down silently from a dark sky, slow descent, ominous, no fire"),
            ("Lớp ozone biến mất khiến tia cực tím thiêu đốt, mọi bề mặt phơi ra ngoài đều cháy sém.",
             "a scorched landscape under harsh ultraviolet light, burnt ground, intense light, bleak",
             "harsh light sweeping across a scorched landscape, faint smoke rising, bleak, slow"),
            ("Áp suất trong tai con người đột ngột thay đổi, cả hành tinh chìm trong cơn choáng váng tức thì.",
             "a clinical extreme close-up of a human ear with a faint pressure shimmer, medical eerie, ominous",
             "a clinical close-up of a human ear, faint pressure shimmer in the air, ominous, very slow push-in"),
            ("Chỉ năm giây thiếu oxy cũng đủ biến cả nền văn minh thành đống đổ nát im lặng dưới bầu trời tối.",
             "a ruined silent city under a dark sky, collapsed buildings, haunting desolate",
             "slow aerial drift over a ruined silent city under a dark sky, dust settling, haunting"),
        ],
    },
    "day9": {
        "title": "Nếu Trái Đất mất từ trường",
        "slug": "neu_mat_tu_truong",
        "story": "What-if: từ trường bảo vệ Trái Đất biến mất.",
        "scenes": [
            ("Nếu từ trường bảo vệ Trái Đất đột nhiên biến mất, lá chắn vô hình giữ chúng ta an toàn khỏi vũ trụ sẽ tan biến.",
             "Earth from space with its faint invisible magnetic shield dissolving, solar wind streaming in, cosmic dramatic",
             "Earth from space, a faint shield dissolving as solar wind streams past, slow cosmic"),
            ("Gió Mặt Trời mang bức xạ chết người ào ạt đổ xuống bề mặt, thứ trước đây luôn bị chặn đứng.",
             "streams of glowing solar radiation pouring down onto Earth's surface, eerie charged sky",
             "glowing radiation streaming down onto a landscape, particles drifting, eerie, slow"),
            ("Cực quang rực rỡ tràn khắp bầu trời mọi nơi, từ xích đạo đến hai cực, đẹp đẽ mà chết chóc.",
             "brilliant green and purple auroras filling the entire sky over a city, beautiful ominous",
             "shimmering auroras rippling across the sky over a city, slow, beautiful ominous"),
            ("Vệ tinh và lưới điện toàn cầu cháy rụi trong bão bức xạ, thế giới mất kết nối chỉ sau vài giờ.",
             "a satellite sparking and failing in orbit above a darkened Earth, dramatic cosmic",
             "a satellite sparking and tumbling in orbit, dark Earth below, slow dramatic"),
            ("Từng chút một, gió Mặt Trời bào mòn bầu khí quyển, thổi nó bay vào không gian như từng xảy ra ở Sao Hoả.",
             "Earth's atmosphere being slowly stripped away into space by solar wind, thinning glow, cosmic bleak",
             "Earth's atmosphere slowly streaming away into space, thinning glow, very slow cosmic"),
            ("Không còn lớp khí quyển dày, nhiệt độ dao động khắc nghiệt, sự sống trên bề mặt dần lụi tàn.",
             "a barren reddish Mars-like Earth landscape under a thin sky, dead ground, bleak desolate",
             "slow pan over a barren Mars-like landscape under a thin sky, dust drifting, bleak"),
            ("Trái Đất dần biến thành một hành tinh chết khô cằn, giống hệt người hàng xóm Sao Hoả đỏ quạch.",
             "Earth as a dry reddish dead planet seen from space, atmosphere gone, haunting cosmic",
             "Earth as a dry red dead planet in space, slow zoom out, haunting"),
        ],
    },
    "day10": {
        "title": "Nếu tất cả núi lửa phun cùng lúc",
        "slug": "neu_nui_lua_phun",
        "story": "What-if: mọi núi lửa trên Trái Đất phun trào cùng lúc.",
        "scenes": [
            ("Nếu mọi núi lửa trên Trái Đất cùng phun trào trong một khoảnh khắc, bầu trời sẽ biến mất sau bức màn tro bụi.",
             "dozens of volcanoes erupting simultaneously across a landscape, massive ash columns, apocalyptic",
             "multiple volcanoes erupting across a landscape, towering ash columns rising, epic dramatic slow"),
            ("Hàng tỉ tấn tro bụi và khí lưu huỳnh bắn lên cao, che kín Mặt Trời chỉ trong vài ngày.",
             "a massive ash cloud blotting out the sun over a darkened landscape, ominous orange glow",
             "a vast ash cloud spreading across the sky, the sun dimming behind it, ominous slow"),
            ("Cả hành tinh chìm vào bóng tối, một mùa đông núi lửa lạnh giá kéo dài bao trùm Trái Đất.",
             "a dark ash-covered world in perpetual grey twilight, bleak volcanic winter landscape",
             "slow drift over a grey ash-covered landscape in dim twilight, faint ash falling, bleak"),
            ("Nhiệt độ toàn cầu lao dốc, mưa axit trút xuống, cây cối và mùa màng chết hàng loạt.",
             "a dead grey forest under acid rain and ashfall, withered crops, bleak desolate",
             "acid rain and ash falling over a dead grey forest, slow, bleak desolate"),
            ("Dung nham nuốt chửng các thành phố gần núi lửa, biến chúng thành tro tàn bốc khói nghi ngút.",
             "rivers of glowing lava engulfing a ruined city, molten flows, smoke, apocalyptic dramatic",
             "glowing lava slowly flowing over a ruined city, smoke rising, apocalyptic slow"),
            ("Loài người tranh giành chút thức ăn cuối cùng dưới một bầu trời không bao giờ còn thấy ánh nắng.",
             "survivors huddled in a dark ashen wasteland under a sunless sky, faint firelight, grim",
             "survivors around a faint fire in a dark ashen wasteland, slow, grim"),
            ("Một khoảnh khắc Trái Đất nổi giận cũng đủ đẩy sự sống đến sát bờ vực diệt vong.",
             "a desolate ash-buried landscape under a dark sky, ruins barely visible, haunting",
             "slow aerial drift over an ash-buried desolate landscape, haunting"),
        ],
    },
    "day11": {
        "title": "Nếu nước biển dâng 100 mét",
        "slug": "neu_nuoc_bien_dang",
        "story": "What-if: mực nước biển dâng thêm 100 mét.",
        "scenes": [
            ("Nếu mực nước biển dâng thêm một trăm mét, những thành phố ven biển lớn nhất thế giới sẽ chìm dưới đại dương.",
             "a coastal megacity half-submerged under risen sea, only skyscraper tops above water, dramatic",
             "slow aerial over a half-submerged city, only skyscraper tops above the water, calm eerie"),
            ("New York, Thượng Hải, Mumbai biến mất dưới làn nước, chỉ còn vài đỉnh toà nhà chọc trời nhô lên.",
             "skyscraper tops emerging from a vast calm ocean where a city once stood, surreal desolate",
             "skyscraper tops poking from a vast calm sea, gentle waves, surreal, slow"),
            ("Hàng tỉ người phải tháo chạy vào sâu trong lục địa, những cuộc di cư lớn nhất lịch sử bắt đầu.",
             "massive crowds of refugees fleeing inland away from a flooded coast, grim dramatic sky",
             "a vast crowd trekking inland from a flooded coastline, grim, slow"),
            ("Những vùng đồng bằng màu mỡ từng nuôi sống nhân loại nay nằm im lìm dưới đáy biển mới.",
             "fertile farmland submerged under shallow sea, drowned fields, eerie underwater light",
             "sunlight rippling over submerged drowned farmland, slow, eerie"),
            ("Các thành phố ngập nước trở thành những nghĩa địa im lìm dưới lòng đại dương xanh thẳm.",
             "a drowned underwater city street with fish swimming between buildings, eerie blue, haunting",
             "slow drift through a drowned underwater city street, fish swimming, eerie blue"),
            ("Loài người co cụm trên những vùng đất cao còn sót lại, tranh giành không gian ngày một chật hẹp.",
             "dense crowded settlements packed on remaining highlands above water, grim overcrowded",
             "slow aerial over crowded settlements on a shrinking highland above the sea, grim"),
            ("Bản đồ thế giới được vẽ lại hoàn toàn, và phần lớn lịch sử loài người nằm lại dưới đáy nước.",
             "a half-drowned Earth from space with shrunken continents and vast oceans, haunting cosmic",
             "Earth from space with expanded oceans and shrunken land, slow zoom, haunting"),
        ],
    },
    "day12": {
        "title": "Nếu một hố đen bay qua Hệ Mặt Trời",
        "slug": "neu_ho_den_bay_qua",
        "story": "What-if: một hố đen lang thang đi vào Hệ Mặt Trời.",
        "scenes": [
            ("Nếu một hố đen lang thang lặng lẽ tiến vào Hệ Mặt Trời, chúng ta sẽ không nhìn thấy nó cho đến khi quá muộn.",
             "a dark rogue black hole distorting starlight as it drifts into the solar system, cosmic eerie",
             "a black hole bending starlight as it drifts through space, slow cosmic, eerie"),
            ("Lực hấp dẫn khủng khiếp của nó kéo lệch quỹ đạo các hành tinh, gieo hỗn loạn khắp Hệ Mặt Trời.",
             "planets pulled off their orbits around the sun by a black hole's gravity, cosmic chaos dramatic",
             "planets drifting off their orbits toward a distant black hole, slow cosmic dramatic"),
            ("Trái Đất bị giật khỏi quỹ đạo quen thuộc, Mặt Trời dần xa và nhỏ lại trên bầu trời.",
             "Earth drifting away from a shrinking distant sun into darkness, cold cosmic, bleak",
             "Earth drifting away as the sun shrinks in the distance, slow, cold cosmic"),
            ("Khi đến gần, lực thuỷ triều xé toạc hành tinh, kéo dài vật chất thành những dải dài vô tận.",
             "a planet stretched and torn into long streams of matter by a black hole, spaghettification, cosmic",
             "a planet stretching into long streams of matter toward a black hole, slow cosmic dramatic"),
            ("Bầu trời đêm méo mó kỳ dị khi ánh sáng các vì sao bị bẻ cong quanh vành chân trời sự kiện.",
             "a night sky grotesquely warped, starlight bending around a black hole's event horizon, surreal cosmic",
             "a warped night sky with starlight bending around a dark event horizon, slow surreal"),
            ("Loài người chỉ còn biết ngước nhìn bầu trời biến dạng, bất lực trước thứ không thể nào chạy thoát.",
             "tiny human silhouettes looking up at a vast warped sky with a black hole, awe and terror, dramatic",
             "small silhouettes gazing up at a vast warped sky, slow, awe and dread"),
            ("Trong vũ trụ bao la, một vị khách vô hình cũng đủ xoá sổ cả một thế giới chỉ trong lặng lẽ.",
             "the solar system in chaos around a dark black hole, planets scattered, haunting cosmic",
             "slow cosmic view of a scattered solar system around a black hole, haunting"),
        ],
    },
    "day13": {
        "title": "Nếu loài côn trùng biến mất hoàn toàn",
        "slug": "neu_con_trung_bien_mat",
        "story": "What-if: mọi loài côn trùng trên Trái Đất biến mất.",
        "scenes": [
            ("Nếu mọi loài côn trùng trên Trái Đất đột nhiên biến mất, sự sụp đổ sẽ bắt đầu một cách hết sức âm thầm.",
             "a silent empty green meadow with no insects, eerie stillness, soft daylight, subtly wrong",
             "slow push-in over a silent still meadow, no movement at all, eerie quiet, soft light"),
            ("Không còn ong và côn trùng thụ phấn, phần lớn cây trồng ngừng kết trái chỉ sau một mùa duy nhất.",
             "withering fruitless orchards and barren crop fields, dying plants, bleak agricultural",
             "slow pan over withering fruitless orchards, dry leaves drifting, bleak"),
            ("Chuỗi thức ăn rạn vỡ từ dưới lên, chim chóc và các loài nhỏ chết đói hàng loạt.",
             "fallen birds and small animals in a barren landscape, collapsed food chain, grim bleak",
             "slow drift over a barren landscape with fallen birds, grim, desolate"),
            ("Xác động thực vật chất đống không phân huỷ vì không còn côn trùng dọn dẹp tự nhiên.",
             "piles of undecomposed dead leaves and debris in a still silent forest, eerie stagnant, bleak",
             "slow pan over piles of undecomposed debris in a still forest, eerie stagnant"),
            ("Mùa màng thất bát trên toàn cầu, những nạn đói khổng lồ quét qua khắp các châu lục.",
             "vast failed cracked farmland under a harsh sky, global famine, bleak desolate",
             "slow aerial over vast failed cracked farmland, dust drifting, bleak"),
            ("Loài người đứng trên đỉnh chuỗi thức ăn mới nhận ra mình phụ thuộc vào những sinh vật bé nhỏ nhất.",
             "a lone human standing in an empty barren field looking at the dead ground, grim, bleak",
             "a lone figure standing in an empty barren field, slow push-in, grim"),
            ("Những sinh vật ta luôn xem thường hoá ra lại chính là thứ giữ cho cả thế giới này sống sót.",
             "a single dead bee on cracked dry earth, extreme macro, symbolic haunting, bleak",
             "extreme macro of a single still bee on cracked earth, faint dust, slow, haunting"),
        ],
    },
    "day14": {
        "title": "Nếu Mặt Trời phình thành sao khổng lồ đỏ",
        "slug": "neu_mat_troi_phinh_to",
        "story": "What-if: Mặt Trời phình to thành sao khổng lồ đỏ.",
        "scenes": [
            ("Nếu Mặt Trời bắt đầu phình to thành một ngôi sao khổng lồ đỏ, nó sẽ nuốt chửng mọi thứ trên đường đi.",
             "a vast swollen red giant sun filling the sky over a landscape, ominous red glow, epic cosmic",
             "a swollen red sun slowly growing larger in the sky over a landscape, ominous epic slow"),
            ("Sao Thuỷ và Sao Kim tan chảy rồi bị nuốt trọn vào lớp khí khổng lồ đang nở rộng của Mặt Trời.",
             "an inner planet melting and being engulfed by an expanding red sun, cosmic fiery dramatic",
             "a planet melting into an expanding red sun's outer layers, slow cosmic fiery"),
            ("Trên Trái Đất, đại dương sôi sục bốc hơi, cả bầu trời rực lên một màu đỏ ngột ngạt.",
             "Earth's oceans boiling and evaporating under a giant red sun, steam rising, red sky, apocalyptic",
             "oceans boiling and steaming under a giant red sun, vapor rising, red sky, slow dramatic"),
            ("Đá nóng chảy, các lục địa biến thành những biển dung nham đỏ rực dưới sức nóng kinh hoàng.",
             "continents turning into glowing molten lava seas under a red giant sun, apocalyptic fiery",
             "a landscape melting into glowing lava under a red sun, slow molten flow, apocalyptic"),
            ("Cuối cùng, lớp khí của Mặt Trời chạm tới quỹ đạo Trái Đất, và hành tinh của chúng ta bốc hơi.",
             "Earth being engulfed and vaporized by the outer layers of a red giant sun, cosmic fiery dramatic",
             "Earth dissolving into the glowing outer layers of a red sun, slow cosmic, dramatic"),
            ("Mọi dấu vết của loài người, mọi câu chuyện và ký ức, tan biến đi mà không còn lại gì.",
             "a faint dissolving silhouette of Earth's remains in solar fire, symbolic haunting cosmic",
             "faint glowing remains drifting in solar fire, slow fade-like drift, haunting"),
            ("Số phận này đang chờ Trái Đất sau năm tỉ năm, một lời nhắc rằng không có gì là vĩnh cửu.",
             "a serene distant red giant sun in deep space where Earth once orbited, empty, haunting cosmic",
             "a distant red giant sun in space where Earth once was, slow zoom out, haunting"),
        ],
    },
}
